// create data
export const USER_DATA_CREATE = 'CREATE_USER_DATA';
export const MENU_DATA_CREATE = 'CREATE_MENU_DATA';
export const MENU_COLLAPSE_SET = 'MENU_COLLAPSE_SET';
export const ACTIVE_MENU_SET = 'ACTIVE_MENU_SET';
export const ROUTE_DATA_CREATE = 'CREATE_ROUTE_DATA';
export const CONTAINER_LOADING_DATA_CREATE = 'CREATE_CONTAINER_LOADING_DATA';
export const CONTAINER_LOADED_DATA_CREATE = 'CREATE_CONTAINER_LOADED_DATA';
export const SET_ASIDE_HIDE = 'SET_ASIDE_HIDE';

export const SET_THEME = 'SET_THEME';
export const SET_SETTING = 'SET_SETTING';

